receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlp/loki:
    endpoint: loki:3100
    tls:
      insecure: true

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]
      
  telemetry:
    logs:
      level: info