apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: Prometheus
      tracesToLogsV2:
        datasourceUid: Loki
        customQuery: true
        query: '{exporter="OTLP"} | json | resources_service_name="${__tags.service.name}" |= "${__tags.traceId}"'
      tracesToMetrics:
        datasourceUid: Prometheus
        tags:
          - key: service.name
            value: service_name
          - key: span.name
            value: span_name
        queries:
          - query: 'authors_operations_total{$__tags}[$__range]'
            link_label: 'Authors Operations Total'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: Loki