apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: Prometheus
      tracesToLogsV2:
        datasourceUid: Loki
        customQuery: true
        query: '{job="${__span.tags["service.namespace"]}/${__span.tags["service.name"]}"} |= "${__span.traceId}"'
      tracesToMetrics:
        datasourceUid: Prometheus
        tags:
          - key: service.name
            value: server
        queries:
          - query: 'sum by(client, server)(rate(graphql_datafetcher_milliseconds_bucket($__tags)[$__rate_interval]))'
            link_label: 'Request rate'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: Loki