apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - datasourceUid: Tempo
          name: trace_id

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: Trace ID
          matcherRegex: 'traceid"\s*:\s*"([a-f0-9]+)"'
          url: '$${__value.raw}'
          datasourceUid: Tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: Prometheus
      tracesToLogsV2:
        datasourceUid: Loki
        customQuery: true
        query: '{job="$${__span.tags["service.name"]}"} |= "$${__span.traceId}"'
      tracesToMetrics:
        datasourceUid: Prometheus
        queries:
          - name: 'Request rate'
            query: 'sum(rate(http_server_request_duration_seconds_count{job="$${__span.tags["service.name"]}"}[5m]))'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: Loki